name: build-test-deploy_secrets
on:
  workflow_dispatch:
  
env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'

    - name: Install, Build, Test
      run: | 
        npm ci
        npm run build --if-present
        npm test 

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      # Simulate a Deployment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::562870963057:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-1

      - name: Deploy to Staging
        run: |
         echo "Deployed to staging environment"
